//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlAssertions.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlAssertions.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;
        ///	&lt;person name=&quot;Piotr&quot; surname=&quot;Rutkowski&quot;&gt;
        ///	&lt;/person&gt;
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;10&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urząd gminy w Terespolu&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;valid-to&gt;2009-20-20&lt;/valid-to&gt;
        ///			&lt;/document&gt;
        ///			&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttributesSetDiffering {
            get {
                return ResourceManager.GetString("AttributesSetDiffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;
        ///	&lt;person name=&quot;Piotr&quot; surname=&quot;Rutkowski&quot;&gt;
        ///	&lt;/person&gt;
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;55&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urząd gminy w Terespolu&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;valid-to&gt;2009-20-20&lt;/valid-to&gt;
        ///			&lt;/document&gt;
        ///			&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttributeValueDiffering {
            get {
                return ResourceManager.GetString("AttributeValueDiffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;
        ///	&lt;person name=&quot;Piotr&quot; surname=&quot;Rutkowski&quot;&gt;
        ///	&lt;/person&gt;
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;10&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urząd gminy w Terespolu&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;valid-to&gt;2009-20-20&lt;/valid-to&gt;
        ///			&lt;/document&gt;
        ///			&lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildNodeNameDiffering {
            get {
                return ResourceManager.GetString("ChildNodeNameDiffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;
        ///	&lt;person name=&quot;Piotr&quot; surname=&quot;Rutkowski&quot;&gt;
        ///	&lt;/person&gt;
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;10&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urząd gminy w Terespolu&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;valid-to&gt;2009-20-20&lt;/valid-to&gt;
        ///			&lt;/document&gt;
        ///			&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildrenCountDiffering {
            get {
                return ResourceManager.GetString("ChildrenCountDiffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;
        ///	&lt;person name=&quot;Piotr&quot; surname=&quot;Rutkowski&quot;&gt;	
        ///	&lt;/person&gt;
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;10&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;passport&quot; number=&quot;999222&quot; /&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urzad gminy w Terespolu&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Equivalent_DeeperLevelChildrenOrderChanged {
            get {
                return ResourceManager.GetString("Equivalent_DeeperLevelChildrenOrderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;	
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;10&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;passport&quot; number=&quot;999222&quot; /&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urzad gminy w Terespolu&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;valid-to&gt;2009-20-20&lt;/valid-to&gt;
        ///			&lt;/document&gt;
        ///		&lt;/documen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Equivalent_TopLevelChildrenOrderChanged {
            get {
                return ResourceManager.GetString("Equivalent_TopLevelChildrenOrderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;
        ///	&lt;person name=&quot;Piotr&quot; surname=&quot;Rutkowski&quot;&gt;	
        ///	&lt;/person&gt;
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;10&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urząd gminy w Terespolu&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;valid-to&gt;2009-20-20&lt;/valid-to&gt;
        ///			&lt;/document&gt;
        ///			&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedXml {
            get {
                return ResourceManager.GetString("ExpectedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;people&gt;
        ///	&lt;person name=&quot;Piotr&quot; surname=&quot;Rutkowski&quot;&gt;
        ///	&lt;/person&gt;
        ///	&lt;person name=&quot;Jan&quot; surname=&quot;Kowalski&quot;&gt;
        ///		&lt;address street=&quot;Mickiewicza&quot; number=&quot;20&quot; /&gt;
        ///		&lt;address street=&quot;Pucka&quot; number=&quot;10&quot; /&gt;
        ///		&lt;documents&gt;
        ///			&lt;document type=&quot;id&quot; number=&quot;ABC102508&quot;&gt;
        ///				&lt;authority&gt;
        ///					&lt;name&gt;Urząd gminy w Kalinowie&lt;/name&gt;
        ///					&lt;autority-id&gt;1234&lt;/autority-id&gt;
        ///				&lt;/authority&gt;
        ///				&lt;valid-from&gt;1999-20-20&lt;/valid-from&gt;
        ///				&lt;valid-to&gt;2009-20-20&lt;/valid-to&gt;
        ///			&lt;/document&gt;
        ///			&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TagContentDiffering {
            get {
                return ResourceManager.GetString("TagContentDiffering", resourceCulture);
            }
        }
    }
}
